module.exports = {
   "created_at":"Tue Aug 25 19:26:32 +0000 2015",
   "id":636258373546213400,
   "id_str":"636258373546213380",
   "text":"RT @Sportsnet: Our #Raptors podcast talked about @JValanciunas with the director of The Other Dream Team http://t.co/SfKkjAN8A2 #RTZ http:/…",
   "source":"<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
   "truncated":false,
   "in_reply_to_status_id":null,
   "in_reply_to_status_id_str":null,
   "in_reply_to_user_id":null,
   "in_reply_to_user_id_str":null,
   "in_reply_to_screen_name":null,
   "user":{
      "id":2227318080,
      "id_str":"2227318080",
      "name":"Jonas Valanciunas",
      "screen_name":"JValanciunas",
      "location":"From Utena, Lithuania",
      "description":"Toronto Raptor & Proud Lithuanian #ThisIsJonas",
      "url":"http://t.co/se87BHtDj7",
      "entities":{
         "url":{
            "urls":[
               {
                  "url":"http://t.co/se87BHtDj7",
                  "expanded_url":"http://twitter.com/jvalanciunas",
                  "display_url":"twitter.com/jvalanciunas",
                  "indices":[
                     0,
                     22
                  ]
               }
            ]
         },
         "description":{
            "urls":[

            ]
         }
      },
      "protected":false,
      "followers_count":73660,
      "friends_count":94,
      "listed_count":298,
      "created_at":"Mon Dec 02 21:48:34 +0000 2013",
      "favourites_count":107,
      "utc_offset":null,
      "time_zone":null,
      "geo_enabled":false,
      "verified":true,
      "statuses_count":121,
      "lang":"en",
      "contributors_enabled":false,
      "is_translator":false,
      "is_translation_enabled":false,
      "profile_background_color":"C0DEED",
      "profile_background_image_url":"http://pbs.twimg.com/profile_background_images/378800000152112077/qTMM3R_Y.jpeg",
      "profile_background_image_url_https":"https://pbs.twimg.com/profile_background_images/378800000152112077/qTMM3R_Y.jpeg",
      "profile_background_tile":false,
      "profile_image_url":"http://pbs.twimg.com/profile_images/553217692597907457/51EokBwz_normal.jpeg",
      "profile_image_url_https":"https://pbs.twimg.com/profile_images/553217692597907457/51EokBwz_normal.jpeg",
      "profile_banner_url":"https://pbs.twimg.com/profile_banners/2227318080/1414948455",
      "profile_link_color":"0084B4",
      "profile_sidebar_border_color":"FFFFFF",
      "profile_sidebar_fill_color":"DDEEF6",
      "profile_text_color":"333333",
      "profile_use_background_image":true,
      "has_extended_profile":false,
      "default_profile":false,
      "default_profile_image":false,
      "following":false,
      "follow_request_sent":false,
      "notifications":false
   },
   "geo":null,
   "coordinates":null,
   "place":null,
   "contributors":null,
   "retweeted_status":{
      "created_at":"Tue Aug 25 18:38:13 +0000 2015",
      "id":636246217228468200,
      "id_str":"636246217228468224",
      "text":"Our #Raptors podcast talked about @JValanciunas with the director of The Other Dream Team http://t.co/SfKkjAN8A2 #RTZ http://t.co/RN2B0bXN3H",
      "source":"<a href=\"http://www.hootsuite.com\" rel=\"nofollow\">Hootsuite</a>",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":21660529,
         "id_str":"21660529",
         "name":"Sportsnet",
         "screen_name":"Sportsnet",
         "location":"Canada",
         "description":"Canada's sports news, scores, schedules, standings, games & highlights from @NHL, @MLB, @NBA, @NFL, @PremierLeague, @WWE, @RogersCup, @Grandslamcurl & more",
         "url":"http://t.co/zuykezZ7g1",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http://t.co/zuykezZ7g1",
                     "expanded_url":"http://www.sportsnet.ca",
                     "display_url":"sportsnet.ca",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":381051,
         "friends_count":189,
         "listed_count":2195,
         "created_at":"Mon Feb 23 15:31:12 +0000 2009",
         "favourites_count":424,
         "utc_offset":-14400,
         "time_zone":"Eastern Time (US & Canada)",
         "geo_enabled":false,
         "verified":true,
         "statuses_count":85272,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"131516",
         "profile_background_image_url":"http://pbs.twimg.com/profile_background_images/629353142157725697/OFU6TSq3.jpg",
         "profile_background_image_url_https":"https://pbs.twimg.com/profile_background_images/629353142157725697/OFU6TSq3.jpg",
         "profile_background_tile":true,
         "profile_image_url":"http://pbs.twimg.com/profile_images/544593049339183104/wQUAHfFz_normal.jpeg",
         "profile_image_url_https":"https://pbs.twimg.com/profile_images/544593049339183104/wQUAHfFz_normal.jpeg",
         "profile_banner_url":"https://pbs.twimg.com/profile_banners/21660529/1440427788",
         "profile_link_color":"3B94D9",
         "profile_sidebar_border_color":"FFFFFF",
         "profile_sidebar_fill_color":"EFEFEF",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "has_extended_profile":false,
         "default_profile":false,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "is_quote_status":false,
      "retweet_count":15,
      "favorite_count":24,
      "entities":{
         "hashtags":[
            {
               "text":"Raptors",
               "indices":[
                  4,
                  12
               ]
            },
            {
               "text":"RTZ",
               "indices":[
                  113,
                  117
               ]
            }
         ],
         "symbols":[

         ],
         "user_mentions":[
            {
               "screen_name":"JValanciunas",
               "name":"Jonas Valanciunas",
               "id":2227318080,
               "id_str":"2227318080",
               "indices":[
                  34,
                  47
               ]
            }
         ],
         "urls":[
            {
               "url":"http://t.co/SfKkjAN8A2",
               "expanded_url":"http://ow.ly/Rm3Ks",
               "display_url":"ow.ly/Rm3Ks",
               "indices":[
                  90,
                  112
               ]
            }
         ],
         "media":[
            {
               "id":636246217001988100,
               "id_str":"636246217001988096",
               "indices":[
                  118,
                  140
               ],
               "media_url":"http://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
               "media_url_https":"https://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
               "url":"http://t.co/RN2B0bXN3H",
               "display_url":"pic.twitter.com/RN2B0bXN3H",
               "expanded_url":"http://twitter.com/Sportsnet/status/636246217228468224/photo/1",
               "type":"photo",
               "sizes":{
                  "medium":{
                     "w":600,
                     "h":330,
                     "resize":"fit"
                  },
                  "thumb":{
                     "w":150,
                     "h":150,
                     "resize":"crop"
                  },
                  "small":{
                     "w":340,
                     "h":187,
                     "resize":"fit"
                  },
                  "large":{
                     "w":1024,
                     "h":563,
                     "resize":"fit"
                  }
               }
            }
         ]
      },
      "extended_entities":{
         "media":[
            {
               "id":636246217001988100,
               "id_str":"636246217001988096",
               "indices":[
                  118,
                  140
               ],
               "media_url":"http://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
               "media_url_https":"https://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
               "url":"http://t.co/RN2B0bXN3H",
               "display_url":"pic.twitter.com/RN2B0bXN3H",
               "expanded_url":"http://twitter.com/Sportsnet/status/636246217228468224/photo/1",
               "type":"photo",
               "sizes":{
                  "medium":{
                     "w":600,
                     "h":330,
                     "resize":"fit"
                  },
                  "thumb":{
                     "w":150,
                     "h":150,
                     "resize":"crop"
                  },
                  "small":{
                     "w":340,
                     "h":187,
                     "resize":"fit"
                  },
                  "large":{
                     "w":1024,
                     "h":563,
                     "resize":"fit"
                  }
               }
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   },
   "is_quote_status":false,
   "retweet_count":15,
   "favorite_count":0,
   "entities":{
      "hashtags":[
         {
            "text":"Raptors",
            "indices":[
               19,
               27
            ]
         },
         {
            "text":"RTZ",
            "indices":[
               128,
               132
            ]
         }
      ],
      "symbols":[

      ],
      "user_mentions":[
         {
            "screen_name":"Sportsnet",
            "name":"Sportsnet",
            "id":21660529,
            "id_str":"21660529",
            "indices":[
               3,
               13
            ]
         },
         {
            "screen_name":"JValanciunas",
            "name":"Jonas Valanciunas",
            "id":2227318080,
            "id_str":"2227318080",
            "indices":[
               49,
               62
            ]
         }
      ],
      "urls":[
         {
            "url":"http://t.co/SfKkjAN8A2",
            "expanded_url":"http://ow.ly/Rm3Ks",
            "display_url":"ow.ly/Rm3Ks",
            "indices":[
               105,
               127
            ]
         }
      ],
      "media":[
         {
            "id":636246217001988100,
            "id_str":"636246217001988096",
            "indices":[
               139,
               140
            ],
            "media_url":"http://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
            "media_url_https":"https://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
            "url":"http://t.co/RN2B0bXN3H",
            "display_url":"pic.twitter.com/RN2B0bXN3H",
            "expanded_url":"http://twitter.com/Sportsnet/status/636246217228468224/photo/1",
            "type":"photo",
            "sizes":{
               "medium":{
                  "w":600,
                  "h":330,
                  "resize":"fit"
               },
               "thumb":{
                  "w":150,
                  "h":150,
                  "resize":"crop"
               },
               "small":{
                  "w":340,
                  "h":187,
                  "resize":"fit"
               },
               "large":{
                  "w":1024,
                  "h":563,
                  "resize":"fit"
               }
            },
            "source_status_id":636246217228468200,
            "source_status_id_str":"636246217228468224",
            "source_user_id":21660529,
            "source_user_id_str":"21660529"
         }
      ]
   },
   "extended_entities":{
      "media":[
         {
            "id":636246217001988100,
            "id_str":"636246217001988096",
            "indices":[
               139,
               140
            ],
            "media_url":"http://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
            "media_url_https":"https://pbs.twimg.com/media/CNRmkDoW8AA1vBJ.jpg",
            "url":"http://t.co/RN2B0bXN3H",
            "display_url":"pic.twitter.com/RN2B0bXN3H",
            "expanded_url":"http://twitter.com/Sportsnet/status/636246217228468224/photo/1",
            "type":"photo",
            "sizes":{
               "medium":{
                  "w":600,
                  "h":330,
                  "resize":"fit"
               },
               "thumb":{
                  "w":150,
                  "h":150,
                  "resize":"crop"
               },
               "small":{
                  "w":340,
                  "h":187,
                  "resize":"fit"
               },
               "large":{
                  "w":1024,
                  "h":563,
                  "resize":"fit"
               }
            },
            "source_status_id":636246217228468200,
            "source_status_id_str":"636246217228468224",
            "source_user_id":21660529,
            "source_user_id_str":"21660529"
         }
      ]
   },
   "favorited":false,
   "retweeted":false,
   "possibly_sensitive":false,
   "lang":"en"
}